[package]
name = "record_reader"
version = "1.1.0"
authors = ["Alex Roper <alex@aroper.net>"]
edition = "2024"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
digest = {version = "0.10", optional = true}
tempfile = "3.25.0"
thiserror = "1.0"

[dev-dependencies]
sha2 = "0.10"

[features]
default = ["digest"]
